language: java

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2/repository/

services:
  - docker

after_success:
  - docker build -t shahankitturn/demo-ms3 .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push shahankitturn/demo-ms3