apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-ms3-deployment
spec:
  selector:
    matchLabels:
      app: arc-demo-ms3
      component: arc-component
  replicas: 1
  template:
    metadata:
      labels:
        app: arc-demo-ms3
        component: arc-component
    spec:
      containers:
      - name: demo-ms3-pod
        image: shahankitturn/demo-ms3:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9999
      imagePullSecrets:
      - name: default-us-icr-io